name: Java Unit Tests

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Temurin is a popular OpenJDK distribution
          java-version: '17'      # Change to the version your project uses

      # Cache Maven dependencies for faster builds
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      # Run Maven tests
      - name: Run Unit Tests
        run: mvn clean test
