name: CI Test Workflow

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'  # Use temurin instead of adoptopenjdk

    - name: Build with Maven
      run: mvn clean install
      working-directory: ./  # Make sure this points to the directory with pom.xml
